using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;

namespace XFListViewIssue {
    public class ViewModel {
        public ObservableCollection<string> Items { get; set; }

        public ViewModel() {

            Items = new ObservableCollection<string>()
            {
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
                "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                "Aenean vel massa quis mauris vehicula lacinia. Mauris tincidunt sem sed arcu. Phasellus enim erat, vestibulum vel, aliquam a, posuere eu, velit. Etiam neque. Nunc tincidunt ante vitae massa. Integer tempor. Duis ante orci, molestie vitae vehicula venenatis, tincidunt ac pede.",
                "In rutrum. In sem justo, commodo ut, suscipit at, pharetra vitae, orci.",
                "Etiam egestas wisi a erat. Vivamus ac leo pretium faucibus. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Morbi imperdiet, mauris ac auctor dictum, nisl ligula egestas nulla, et sollicitudin sem purus in lacus. Etiam posuere lacus quis dolor. Donec quis nibh at felis congue commodo.",
                "Integer malesuada.",
            };

        }

    }

}
